volumes:
  db_data:
  static:
  media:

services:
  backend:
    build: ./backend/
    env_file: .env
    container_name: prodex_site
    volumes:
      #- .:/app  # Чтобы изменения отражались сразу
      - db_data:/app/instance
      - media:/app/media
      - static:/app/app/static
  gateway:
      build: ./nginx/
      env_file: .env
      volumes:
        - static:/usr/share/nginx/html/
        - media:/media/ 
      depends_on:
        - backend
      ports:
        - 5000:80
