"""init tables

Revision ID: 510852fddeb2
Revises: 
Create Date: 2025-08-26 11:27:48.134372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510852fddeb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_page_text', sa.Text(), nullable=False),
    sa.Column('main_image', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('main_page_text')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.String(length=200), nullable=True),
    sa.Column('header_image', sa.String(length=200), nullable=True),
    sa.Column('content_image', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('site_info')
    op.drop_table('category')
    # ### end Alembic commands ###
