"""Add field about in SiteInfo

Revision ID: 7a64ce366ba5
Revises: 510852fddeb2
Create Date: 2025-08-27 11:20:27.884070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a64ce366ba5'
down_revision = '510852fddeb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_product')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('site_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_info', schema=None) as batch_op:
        batch_op.drop_column('about')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('short_description', sa.TEXT(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('thumbnail', sa.VARCHAR(length=200), nullable=True),
    sa.Column('header_image', sa.VARCHAR(length=200), nullable=True),
    sa.Column('content_image', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
